# Generated by Django 5.2.7 on 2025-11-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(max_length=20, unique=True, verbose_name='Tipul Dietei')),
                ('text', models.TextField(verbose_name='Citatul Motivațional')),
            ],
        ),
        migrations.CreateModel(
            name='Exercitiu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100, verbose_name='Titlul Exercițiului/Antrenamentului')),
                ('locatie', models.CharField(choices=[('acasa', 'Acasă'), ('sala', 'La Sală'), ('aer_liber', 'Aer Liber')], max_length=20, verbose_name='Locație')),
                ('obiectiv', models.CharField(choices=[('slabit', 'Slăbire (Deficit)'), ('mentinere', 'Menținere'), ('ingrasare', 'Masă Musculară')], max_length=20, verbose_name='Obiectiv')),
                ('descriere', models.TextField(verbose_name='Descriere')),
                ('tag', models.CharField(max_length=50, verbose_name='Taguri (ex: Cardio, Forță)')),
            ],
        ),
        migrations.CreateModel(
            name='Reteta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100, verbose_name='Numele Rețetei')),
                ('tip', models.CharField(choices=[('slabit', 'Slăbire (Deficit)'), ('mentinere', 'Menținere'), ('ingrasare', 'Masă Musculară')], max_length=20, verbose_name='Tipul Dietei')),
                ('masa', models.CharField(choices=[('mic_dejun', 'Mic Dejun'), ('pranz', 'Prânz'), ('cina', 'Cină')], max_length=20, verbose_name='Masa Zilei')),
                ('zi', models.IntegerField(verbose_name='Ziua Planului')),
                ('kcal', models.IntegerField(verbose_name='Calorii')),
                ('img_url_placeholder', models.CharField(max_length=255, verbose_name='URL Placeholder Imagine')),
            ],
        ),
    ]
