# Generated by Django 5.2.7 on 2026-04-11 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal', models.CharField(choices=[('lose', 'Slăbire'), ('maintain', 'Menținere'), ('gain', 'Îngrășare')], max_length=20)),
                ('description', models.TextField()),
                ('calories_per_day', models.IntegerField()),
                ('is_insulin_friendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=255)),
                ('environment', models.CharField(choices=[('home', 'Acasă'), ('gym', 'Sală'), ('outdoor', 'Afară')], max_length=20)),
                ('youtube_url', models.URLField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Începător'), ('medium', 'Intermediar'), ('hard', 'Avansat')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('goal', models.CharField(choices=[('lose', 'Slăbire'), ('maintain', 'Menținere'), ('gain', 'Îngrășare')], default='maintain', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='citat',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='citat',
            name='tip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exercitiu',
            name='descriere',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='exercitiu',
            name='locatie',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exercitiu',
            name='obiectiv',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='exercitiu',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exercitiu',
            name='titlu',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='img_url_placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='kcal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='masa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='nume',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='tip',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reteta',
            name='zi',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Utilizator'), ('assistant', 'Asistent')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', 'Mic dejun'), ('lunch', 'Prânz'), ('dinner', 'Cină'), ('snack', 'Gustare')], max_length=20)),
                ('food_name', models.CharField(max_length=200)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField(default=0)),
                ('carbs', models.FloatField(default=0)),
                ('fat', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='MealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meals/')),
                ('estimated_calories', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('calories', models.IntegerField()),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='my_app.diet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('lose', 'Slăbire'), ('maintain', 'Menținere'), ('gain', 'Îngrășare')], default='maintain', max_length=20)),
                ('is_vip', models.BooleanField(default=False)),
                ('has_insulin_resistance', models.BooleanField(default=False)),
                ('suspected_insulin_resistance', models.BooleanField(default=False)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VipPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount_eur', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
