# Generated by Django 5.2.7 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_diet_workout_alter_citat_text_alter_citat_tip_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['day', 'meal_type']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='day',
            field=models.IntegerField(choices=[(1, 'Luni'), (2, 'Marți'), (3, 'Miercuri'), (4, 'Joi'), (5, 'Vineri'), (6, 'Sâmbătă'), (7, 'Duminică')], default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Mic dejun'), ('lunch', 'Prânz'), ('dinner', 'Cină'), ('snack', 'Gustare')], default='lunch', max_length=20),
        ),
    ]
