# Generated by Django 5.2.7 on 2026-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_recipe_options_recipe_day_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL imagine reprezentativa'),
        ),
        migrations.AddField(
            model_name='workout',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL imagine reprezentativa'),
        ),
    ]
