# Generated by Django 5.2.7 on 2026-04-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_recipe_image_url_workout_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reteta',
            name='carbohidrati',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reteta',
            name='grasimi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reteta',
            name='img_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='reteta',
            name='instructiuni',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reteta',
            name='proteine',
            field=models.IntegerField(default=0),
        ),
    ]
