# Generated by Django 5.2.7 on 2026-04-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_reteta_carbohidrati_reteta_grasimi_reteta_img_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramZilnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_dieta', models.CharField(max_length=30)),
                ('zi', models.IntegerField()),
                ('trezire', models.CharField(max_length=10)),
                ('mic_dejun_ora', models.CharField(max_length=10)),
                ('gustare1_ora', models.CharField(max_length=10)),
                ('antrenament_ora', models.CharField(max_length=10)),
                ('antrenament_tip', models.CharField(max_length=100)),
                ('pranz_ora', models.CharField(max_length=10)),
                ('gustare2_ora', models.CharField(max_length=10)),
                ('cina_ora', models.CharField(max_length=10)),
                ('relaxare_ora', models.CharField(max_length=10)),
                ('somn_ora', models.CharField(max_length=10)),
                ('ore_somn', models.FloatField(default=8)),
                ('sfat_somn', models.CharField(blank=True, max_length=300)),
                ('sfat_zi', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='exercitiu',
            name='durata_minute',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='exercitiu',
            name='img_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='exercitiu',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exercitiu',
            name='zi',
            field=models.IntegerField(default=0),
        ),
    ]
